// Fonte única da verdade para ENUMs do banco de dados

export const CARGO = {
  PROPRIETARIO: 'PROPRIETARIO',
  FUNCIONARIO: 'FUNCIONARIO',
  VENDEDOR: 'VENDEDOR',
};

export const COMPRIMENTO = {
  P: 'P',
  M: 'M',
  G: 'G',
};

export const STATUS_AGENDAMENTO = {
  AGENDADO: 'AGENDADO',
  EXECUTADO: 'EXECUTADO',
  CANCELADO: 'CANCELADO',
};

export const CATEGORIA_PROCEDIMENTO = {
  SERVICO_CABELO: 'SERVICO_CABELO',
  PRODUTO_APLICADO: 'PRODUTO_APLICADO',
  SERVICO_ESTETICA: 'SERVICO_ESTETICA',
};

export const TIPO_DESPESA = {
  ALUGUEL: 'ALUGUEL',
  ENERGIA: 'ENERGIA',
  AGUA: 'AGUA',
  INTERNET: 'INTERNET',
  MATERIAL: 'MATERIAL',
  EQUIPAMENTO: 'EQUIPAMENTO',
  FORNECEDOR: 'FORNECEDOR',
  FUNCIONARIO: 'FUNCIONARIO',
  OUTRO: 'OUTRO',
  PRODUTO: 'PRODUTO',
};
